esphome:
  name: si4432-sniffer
  friendly_name: Si4432 Sniffer
  min_version: 2025.4.0
  name_add_mac_suffix: false

external_components:
  - source:
      type: git
      url: https://github.com/pchdomotichome/esphome
      ref: main
    components: [si4432]
    refresh: 0s
      

esp32:
  board: esp32dev


# Enable logging
logger:
  level: VERBOSE
# Enable Home Assistant API
api:

# Allow Over-The-Air updates
ota:
- platform: esphome

wifi:
  networks:
    ssid: !secret wifi_ssid
    password: !secret wifi_password
    manual_ip:
      static_ip: 192.168.30.145
      gateway: 192.168.30.1
      subnet: 255.255.255.0
      dns1: 192.168.1.243
      dns2: 8.8.8.8
  reboot_timeout: 2min
  fast_connect: on

spi:
  id: spi_bus
  clk_pin: GPIO18
  mosi_pin: GPIO23
  miso_pin: GPIO19
 
si4432:
    id: si4432_chip
    spi_id: spi_bus
    cs_pin: GPIO16