esphome:
  name: si4432_sniffer
  friendly_name: Si4432 Sniffer

external_components:
  - source:
      type: local
      path: "./si4432"

esp32:
  board: esp32dev

logger:
  level: DEBUG

wifi:
  ssid: "TU_SSID"
  password: "TU_PASSWORD"

spi:
  clk_pin: GPIO18
  mosi_pin: GPIO23
  miso_pin: GPIO19

si4432:
  cs_pin: GPIO5
