esphome:
  name: si4432_sniffer
  friendly_name: SI4432 Sniffer

esp32:
  board: esp32dev
  framework:
    type: arduino

logger:

spi:
  clk_pin: GPIO18
  mosi_pin: GPIO23
  miso_pin: GPIO19

external_components:
  - source:
      type: local
      path: ./components

si4432:
  cs_pin: GPIO16
  irq_pin: GPIO4