
esphome:
  name: si4432_sniffer
  friendly_name: SI4432 Sniffer

esp32:
  board: esp32dev

external_components:
  - source:
      type: local
      path: components

logger:
  level: DEBUG

spi:
  clk_pin: GPIO18
  mosi_pin: GPIO23
  miso_pin: GPIO19

si4432:
  cs_pin: GPIO16  # Chip Select
  irq_pin: GPIO4  # nIRQ del SI4432
